-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["LiuDing_Tiles_veteran BBQ_40"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_48"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_41"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_49"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_42"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_50"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_43"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_51"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_44"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_52"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_45"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_53"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_64"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_68"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_65"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_69"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_66"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_70"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_67"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_71"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_72"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_76"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_73"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_77"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_74"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_78"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_75"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_79"} }}
overlayMap["LiuDing_Tiles_veteran BBQ_80"] = {{ name = "other", tiles = {"LiuDing_Tiles_veteran BBQ_81"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
