AmmoType.register("firearms:bullets_22", "Base.Bullets22")
AmmoType.register("firearms:bullets_10mm", "Base.Bullets10mm")
AmmoType.register("firearms:bullets_762x51", "Base.762x51Bullets")
AmmoType.register("firearms:bullets_762x39", "Base.762x39Bullets")
AmmoType.register("firearms:bullets_30_06", "Base.Bullets3006")
AmmoType.register("firearms:bullets_44_40", "Base.Bullets4440")
AmmoType.register("firearms:bullets_357", "Base.Bullets357")

FirearmsTags = {}
FirearmsTags.firearmsService = ItemTag.register("firearms:firearms_service")
FirearmsTags.firearmsSuppressor = ItemTag.register("firearms:suppressor")
FirearmsTags.firearmsSuppressorCrafted = ItemTag.register("firearms:suppressor_crafted")
FirearmsTags.firearmsSuppressorCraftedBad = ItemTag.register("firearms:suppressor_crafted_bad")
FirearmsTags.firearmsCompensator = ItemTag.register("firearms:compensator")
FirearmsTags.firearmsUnderBarrelRail = ItemTag.register("firearms:under_barrel_rail")
