--
-- Created by IntelliJ IDEA.
-- User: RJ
-- Date: 25/01/2018
-- Time: 09:20
-- To change this template use File | Settings | File Templates.
--
ISCarMechanicsOverlay.CarList["Base.fr_am_gremlin_73"] = {imgPrefix = "smallcar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ag_hmmwv_92_2d_mil"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ag_hmmwv_92_4d_mil"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ag_m151_85_mil"] = {imgPrefix = "offroad_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ag_m35_88_mil"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ag_m49_88_mil"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_bu_wildcat_68"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_bu_wildcat_68_convert"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ca_deville_79"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ca_deville_79_coupe"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_3100_51"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_3100_51_offroad"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_3100_51_old"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_astro_92"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_belair_55"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_belair_55_taxi"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_blazer_87"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_blazer_87_mil"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_blazer_87_offroad"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_blazer_87_police"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_71_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_71_lb_ranger"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_71_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_71_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_71_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_lb_mil"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_utility"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_utility_fire"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_c10_87_utility_mccoy"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_caprice_87"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_caprice_87_police"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_caprice_87_taxi"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_caprice_87_wag"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_chevelle_70"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_chevelle_70_convert"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_corvette_79"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_elcamino_70"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_impala_71"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_montecarlo_83"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_montecarlo_83_ttop"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_ext_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_ext_lb_ranger"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_ext_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_ext_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_ext_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_lb_ranger"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_s10_91_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_stepvan_80"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_stepvan_80_police"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_suburban_87"] = {imgPrefix = "stationwagon_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_ch_suburban_87_offroad"] = {imgPrefix = "stationwagon_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_da_240z_73"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_charger_69"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_charger_69_daytona"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_charger_69_general"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_dakota_89_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_dakota_89_shelby_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_ram_90_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_ram_90_moving"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_ram_90_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_ram_90_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_ram_90_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_do_viper_92"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fl_bounder_86"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_7810_89"] = {imgPrefix = "offroad_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_b700_prisonlong"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_b700_schoollong"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_b700_schoolshort"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_bronco_80"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_bronco_80_offroad"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85_coupe"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85_police"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85_taxi"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85_wag"] = {imgPrefix = "stationwagon_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_85_wagtaxi"] = {imgPrefix = "stationwagon_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_92"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_crownvic_92_police"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_econoline_86"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_econoline_86_ambulance"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_econoline_86_florist"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_econoline_rv_86"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_explorer_93"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_explorer_93_jurassic"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f350_80"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f350_80_offroad"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f350_80_offroadquad"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f350_80_quad"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f350_ambulance_80"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_boxlarge"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_boxmed"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_dump"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_flatmed"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_flatsmall"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_fuel"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_pickup"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_f700_90_propane"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_falcon_73"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_falcon_73_pursuit"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_mustang_64"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_mustang_64_convert"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_fo_pinto_73"] = {imgPrefix = "smallcar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_gm_newlook_70_35foot"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_gr_llv_89"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_is_nrr_93_boxmed"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_is_nrr_93_dump"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_is_nrr_93_flatmed"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_is_nrr_93_flatsmall"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_cherokee_93"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_cherokee_93_offroad"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_cherokee_93_police"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_wagoneer_91"] = {imgPrefix = "suv_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_wrangler_92"] = {imgPrefix = "offroad_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_wrangler_92_jurassic"] = {imgPrefix = "offroad_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_je_wrangler_92_offroad"] = {imgPrefix = "offroad_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_pi_engine_90_fire"] = {imgPrefix = "van_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_pe_359_82_short"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_pe_359_82_med"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_pe_359_82_long"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_po_gto_65"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_po_transam_77"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_po_transam_77_bandit"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_po_transam_77_ttop"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_celica_91"] = {imgPrefix = "sportscar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_corolla_90"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_corolla_90_coupe"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_corolla_90_hatch"] = {imgPrefix = "smallcar_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_hilux_83_lb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_hilux_83_offroadlb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_hilux_83_offroadsb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_to_hilux_83_sb"] = {imgPrefix = "truck_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_vo_240_93"] = {imgPrefix = "4door_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_vo_240_93_wagon"] = {imgPrefix = "stationwagon_", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.fr_vw_beetle_72"] = {imgPrefix = "4door_", x=10,y=0};
--[[
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_camper_scamp"] = {imgPrefix = "", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_ch_3100_51"] = {imgPrefix = "", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_fuel_medium"] = {imgPrefix = "", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_fuel_small"] = {imgPrefix = "", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_moving_large"] = {imgPrefix = "", x=10,y=0};
ISCarMechanicsOverlay.CarList["Base.Trailer_fr_moving_medium"] = {imgPrefix = "", x=10,y=0};
--]]
ISCarMechanicsOverlay.PartList["FRBumperFront"] = {img="fr_front_bumper", vehicles = {}};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["truck_"] = {x=84,y=111,x2=207,y2=130};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["van_"] = {x=79,y=110,x2=206, y2=131};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["4door_"] = {x=81,y=111,x2=203,y2=131};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["smallcar_"] = {x=88,y=125,x2=202,y2=148};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["stationwagon_"] = {x=86,y=110,x2=201,y2=127};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["suv_"] = {x=69,y=113,x2=221,y2=135};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["offroad_"] = {x=69,y=129,x2=217,y2=152};
ISCarMechanicsOverlay.PartList["FRBumperFront"].vehicles["sportscar_"] = {x=92,y=118,x2=199,y2=145};

ISCarMechanicsOverlay.PartList["FRBumperRear"] = {img="fr_rear_bumper", vehicles = {}};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["truck_"] = {x=84,y=460,x2=207,y2=480};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["van_"] = {x=76,y=468,x2=209, y2=485};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["4door_"] = {x=77,y=471,x2=207,y2=486};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["smallcar_"] = {x=88,y=449,x2=202,y2=468};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["stationwagon_"] = {x=85,y=463,x2=202,y2=484};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["suv_"] = {x=69,y=463,x2=221,y2=484};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["offroad_"] = {x=69,y=464,x2=217,y2=484};
ISCarMechanicsOverlay.PartList["FRBumperRear"].vehicles["sportscar_"] = {x=89,y=445,x2=202,y2=468};

ISCarMechanicsOverlay.PartList["FRRoof"] = {img="fr_roof", vehicles = {}};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["truck_"] = {x=106,y=256,x2=185,y2=298};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["van_"] = {x=97,y=221,x2=188, y2=438};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["4door_"] = {x=105,y=282,x2=179,y2=367};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["smallcar_"] = {x=77,y=165,x2=178,y2=390};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["stationwagon_"] = {x=110,y=267,x2=177,y2=437};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["suv_"] = {x=95,y=266,x2=195,y2=427};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["offroad_"] = {x=93,y=307,x2=193,y2=427};
ISCarMechanicsOverlay.PartList["FRRoof"].vehicles["sportscar_"] = {x=116,y=301,x2=175,y2=352};

ISCarMechanicsOverlay.PartList["FRConRoof"] = {img="fr_roof", vehicles = {}};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["truck_"] = {x=106,y=256,x2=185,y2=298};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["van_"] = {x=97,y=221,x2=188, y2=438};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["4door_"] = {x=105,y=282,x2=179,y2=367};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["smallcar_"] = {x=77,y=165,x2=178,y2=390};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["stationwagon_"] = {x=110,y=267,x2=177,y2=437};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["suv_"] = {x=95,y=266,x2=195,y2=427};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["offroad_"] = {x=93,y=307,x2=193,y2=427};
ISCarMechanicsOverlay.PartList["FRConRoof"].vehicles["sportscar_"] = {x=116,y=301,x2=175,y2=352};
