-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["cathaya_furniture_01_0"] = {{ name = "other", tiles = {"cathaya_furniture_01_8"} }}
overlayMap["cathaya_furniture_01_1"] = {{ name = "other", tiles = {"cathaya_furniture_01_9"} }}
overlayMap["cathaya_furniture_01_2"] = {{ name = "other", tiles = {"cathaya_furniture_01_10"} }}
overlayMap["cathaya_furniture_01_3"] = {{ name = "other", tiles = {"cathaya_furniture_01_11"} }}
overlayMap["cathaya_furniture_01_4"] = {{ name = "other", tiles = {"cathaya_furniture_01_12"} }}
overlayMap["cathaya_furniture_01_5"] = {{ name = "other", tiles = {"cathaya_furniture_01_13"} }}
overlayMap["cathaya_furniture_01_6"] = {{ name = "other", tiles = {"cathaya_furniture_01_14"} }}
overlayMap["cathaya_furniture_01_7"] = {{ name = "other", tiles = {"cathaya_furniture_01_15"} }}
overlayMap["cathaya_furniture_01_56"] = {{ name = "other", tiles = {"cathaya_furniture_01_64"} }}
overlayMap["cathaya_furniture_01_57"] = {{ name = "other", tiles = {"cathaya_furniture_01_65"} }}
overlayMap["cathaya_furniture_01_58"] = {{ name = "other", tiles = {"cathaya_furniture_01_66"} }}
overlayMap["cathaya_furniture_01_59"] = {{ name = "other", tiles = {"cathaya_furniture_01_67"} }}
overlayMap["cathaya_furniture_01_60"] = {{ name = "other", tiles = {"cathaya_furniture_01_68"} }}
overlayMap["cathaya_furniture_01_61"] = {{ name = "other", tiles = {"cathaya_furniture_01_69"} }}
overlayMap["cathaya_furniture_01_62"] = {{ name = "other", tiles = {"cathaya_furniture_01_70"} }}
overlayMap["cathaya_furniture_01_63"] = {{ name = "other", tiles = {"cathaya_furniture_01_71"} }}
overlayMap["cathaya_furniture_01_80"] = {{ name = "other", tiles = {"cathaya_furniture_01_88"} }}
overlayMap["cathaya_furniture_01_81"] = {{ name = "other", tiles = {"cathaya_furniture_01_89"} }}
overlayMap["cathaya_furniture_01_82"] = {{ name = "other", tiles = {"cathaya_furniture_01_90"} }}
overlayMap["cathaya_furniture_01_83"] = {{ name = "other", tiles = {"cathaya_furniture_01_91"} }}
overlayMap["cathaya_furniture_01_84"] = {{ name = "other", tiles = {"cathaya_furniture_01_92"} }}
overlayMap["cathaya_furniture_01_85"] = {{ name = "other", tiles = {"cathaya_furniture_01_93"} }}
overlayMap["cathaya_furniture_01_86"] = {{ name = "other", tiles = {"cathaya_furniture_01_94"} }}
overlayMap["cathaya_furniture_01_87"] = {{ name = "other", tiles = {"cathaya_furniture_01_95"} }}
overlayMap["cathaya_furniture_01_96"] = {{ name = "other", tiles = {"cathaya_furniture_01_104"} }}
overlayMap["cathaya_furniture_01_97"] = {{ name = "other", tiles = {"cathaya_furniture_01_105"} }}
overlayMap["cathaya_furniture_01_98"] = {{ name = "other", tiles = {"cathaya_furniture_01_106"} }}
overlayMap["cathaya_furniture_01_99"] = {{ name = "other", tiles = {"cathaya_furniture_01_107"} }}
overlayMap["cathaya_furniture_01_100"] = {{ name = "other", tiles = {"cathaya_furniture_01_108"} }}
overlayMap["cathaya_furniture_01_101"] = {{ name = "other", tiles = {"cathaya_furniture_01_109"} }}
overlayMap["cathaya_furniture_01_102"] = {{ name = "other", tiles = {"cathaya_furniture_01_110"} }}
overlayMap["cathaya_furniture_01_103"] = {{ name = "other", tiles = {"cathaya_furniture_01_111"} }}
overlayMap["cathaya_furniture_01_112"] = {{ name = "other", tiles = {"cathaya_furniture_01_120"} }}
overlayMap["cathaya_furniture_01_113"] = {{ name = "other", tiles = {"cathaya_furniture_01_121"} }}
overlayMap["cathaya_furniture_01_124"] = {{ name = "other", tiles = {"cathaya_furniture_01_126"} }}
overlayMap["cathaya_furniture_01_125"] = {{ name = "other", tiles = {"cathaya_furniture_01_127"} }}
overlayMap["cathaya_furniture_03_8"] = {{ name = "other", tiles = {"cathaya_furniture_03_16"} }}
overlayMap["cathaya_furniture_03_9"] = {{ name = "other", tiles = {"cathaya_furniture_03_17"} }}
overlayMap["cathaya_furniture_03_10"] = {{ name = "other", tiles = {"cathaya_furniture_03_18"} }}
overlayMap["cathaya_furniture_03_11"] = {{ name = "other", tiles = {"cathaya_furniture_03_19"} }}
overlayMap["cathaya_furniture_03_12"] = {{ name = "other", tiles = {"cathaya_furniture_03_20"} }}
overlayMap["cathaya_furniture_03_13"] = {{ name = "other", tiles = {"cathaya_furniture_03_21"} }}
overlayMap["cathaya_furniture_03_14"] = {{ name = "other", tiles = {"cathaya_furniture_03_22"} }}
overlayMap["cathaya_furniture_03_15"] = {{ name = "other", tiles = {"cathaya_furniture_03_23"} }}
overlayMap["cathaya_furniture_04_0"] = {{ name = "other", tiles = {"cathaya_furniture_04_8"} }}
overlayMap["cathaya_furniture_04_1"] = {{ name = "other", tiles = {"cathaya_furniture_04_9"} }}
overlayMap["cathaya_furniture_04_2"] = {{ name = "other", tiles = {"cathaya_furniture_04_10"} }}
overlayMap["cathaya_furniture_04_3"] = {{ name = "other", tiles = {"cathaya_furniture_04_11"} }}
overlayMap["cathaya_furniture_04_4"] = {{ name = "other", tiles = {"cathaya_furniture_04_12"} }}
overlayMap["cathaya_furniture_04_5"] = {{ name = "other", tiles = {"cathaya_furniture_04_13"} }}
overlayMap["cathaya_furniture_04_6"] = {{ name = "other", tiles = {"cathaya_furniture_04_14"} }}
overlayMap["cathaya_furniture_04_7"] = {{ name = "other", tiles = {"cathaya_furniture_04_15"} }}
overlayMap["cathaya_furniture_04_16"] = {{ name = "other", tiles = {"cathaya_furniture_04_24"} }}
overlayMap["cathaya_furniture_04_17"] = {{ name = "other", tiles = {"cathaya_furniture_04_25"} }}
overlayMap["cathaya_furniture_04_18"] = {{ name = "other", tiles = {"cathaya_furniture_04_26"} }}
overlayMap["cathaya_furniture_04_19"] = {{ name = "other", tiles = {"cathaya_furniture_04_27"} }}
overlayMap["cathaya_furniture_04_20"] = {{ name = "other", tiles = {"cathaya_furniture_04_28"} }}
overlayMap["cathaya_furniture_04_21"] = {{ name = "other", tiles = {"cathaya_furniture_04_29"} }}
overlayMap["cathaya_furniture_04_22"] = {{ name = "other", tiles = {"cathaya_furniture_04_30"} }}
overlayMap["cathaya_furniture_04_23"] = {{ name = "other", tiles = {"cathaya_furniture_04_31"} }}
overlayMap["cathaya_furniture_04_32"] = {{ name = "other", tiles = {"cathaya_furniture_04_40"} }}
overlayMap["cathaya_furniture_04_33"] = {{ name = "other", tiles = {"cathaya_furniture_04_41"} }}
overlayMap["cathaya_furniture_04_34"] = {{ name = "other", tiles = {"cathaya_furniture_04_42"} }}
overlayMap["cathaya_furniture_04_35"] = {{ name = "other", tiles = {"cathaya_furniture_04_43"} }}
overlayMap["cathaya_furniture_04_36"] = {{ name = "other", tiles = {"cathaya_furniture_04_44"} }}
overlayMap["cathaya_furniture_04_37"] = {{ name = "other", tiles = {"cathaya_furniture_04_45"} }}
overlayMap["cathaya_furniture_04_38"] = {{ name = "other", tiles = {"cathaya_furniture_04_46"} }}
overlayMap["cathaya_furniture_04_39"] = {{ name = "other", tiles = {"cathaya_furniture_04_47"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap



