local PreventRemoval = require("WeaponSystems/Utils/PreventRemovals")

PreventRemoval.Register({
    -- Magazines
    "MarzGuns.556x45Magazine20_STANAG",
    "MarzGuns.556x45Magazine25_STANAG",
    "MarzGuns.556x45Magazine30_STANAG",
    "MarzGuns.556x45Magazine60_STANAG",
    "MarzGuns.556x45Magazine50_STANAG",
    "MarzGuns.556x45Magazine75_STANAG",
    "MarzGuns.556x45Magazine100_STANAG",
    "MarzGuns.556x45Magazine150_STANAG",
    "MarzGuns.556x45Magazine30_G36",

    "MarzGuns.545x39Magazine30_Bakelite",
    "MarzGuns.545x39Magazine45_Bakelite",
    "MarzGuns.545x39Magazine100_Drum",

    "MarzGuns.9x39Magazine30",

    "MarzGuns.762x39Magazine30",
    "MarzGuns.762x39Magazine75",

    "MarzGuns.3006Clip8",
    "MarzGuns.762x51Magazine20_M14",
    "MarzGuns.762x51Magazine20_FAL",
    "MarzGuns.762x51Magazine20_G3",

    "MarzGuns.762x51Magazine5_M24",

    "MarzGuns.762x51Box100_M60",
    "MarzGuns.3006Magazine20_BAR",

    "MarzGuns.9x19Magazine15_M92FS",
    "MarzGuns.9x19Magazine30_M92FS",
    "MarzGuns.9x19Magazine50_M92FS",
    "MarzGuns.9x19Magazine18_M93R",
    "MarzGuns.9x19Magazine60_M93R",
    "MarzGuns.9x19Magazine13_HIPOWER",
    "MarzGuns.9x19Magazine10_P226",
    "MarzGuns.45Magazine7_M1911",
    "MarzGuns.45Magazine12_USP",
    "MarzGuns.45Magazine20_USP",
    "MarzGuns.50Magazine8_DEAGLE",
    "MarzGuns.50Magazine12_DEAGLE",

    "MarzGuns.762x54Magazine10_SVD",
    "MarzGuns.762x51Magazine5_PSG1",

    "MarzGuns.12GMagazine8_AA12",
    "MarzGuns.12GMagazine20_AA12",

    "MarzGuns.45Magazine30_THOMPSON",
    "MarzGuns.45Magazine20_THOMPSON",
    "MarzGuns.45Magazine100_THOMPSON",
    "MarzGuns.9x19Magazine20_MP5",
    "MarzGuns.9x19Magazine25_MP5",
    "MarzGuns.9x19Magazine30_MP5",
    "MarzGuns.9x19Magazine60_MP5",
    "MarzGuns.9x19Magazine100_MP5",

    -- Animated Attachments
    "MarzGuns.Slide_Lock",
    "MarzGuns.Slide_Fired",
    "MarzGuns.Pump_Lock",
    "MarzGuns.Pump_Fired",
    "MarzGuns.Bolt_Lock",
    "MarzGuns.Bolt_Fired",
    "MarzGuns.Lever_Lock",
    "MarzGuns.Lever_Fired",
    "MarzGuns.Barrel_Close",
    "MarzGuns.Barrel_Open",

    -- Integrated Attachments
    "MarzGuns.FNC_Integrated_Bipod_Folded",
    "MarzGuns.FNC_Integrated_Bipod_Deployed",
    "MarzGuns.M60_Integrated_Bipod_Folded",
    "MarzGuns.M60_Integrated_Bipod_Deployed",
    "MarzGuns.BAR_Integrated_Bipod_Folded",
    "MarzGuns.BAR_Integrated_Bipod_Deployed",
    "MarzGuns.AKS74U_Integrated_Stock_Folded",
    "MarzGuns.AKS74U_Integrated_Stock_Deployed",
    "MarzGuns.ASVAL_Integrated_Stock_Folded",
    "MarzGuns.ASVAL_Integrated_Stock_Deployed",
    "MarzGuns.G36C_Integrated_Stock_Folded",
    "MarzGuns.G36C_Integrated_Stock_Deployed",
    "MarzGuns.G36_Integrated_Stock_Folded",
    "MarzGuns.G36_Integrated_Stock_Deployed",
    "MarzGuns.G36C_Integrated_Rail_Up",
    "MarzGuns.G36C_Integrated_Rail_Down",
    "MarzGuns.M4_Integrated_Rail_Up",
    "MarzGuns.M4_Integrated_Rail_Down",
    "MarzGuns.M4_Integrated_Rail_Left",
    "MarzGuns.M4_Integrated_Rail_Right",
    "MarzGuns.SPAS12_Integrated_Stock_Folded",
    "MarzGuns.SPAS12_Integrated_Stock_Deployed",
    "MarzGuns.SKS_Bayonet_Folded",
    "MarzGuns.SKS_Bayonet_Deployed",
    "MarzGuns.CAR15_Integrated_Stock_Folded",
    "MarzGuns.CAR15_Integrated_Stock_Deployed",
    "MarzGuns.M4A1_Integrated_Stock_Folded",
    "MarzGuns.M4A1_Integrated_Stock_Deployed",
    "MarzGuns.XM177_Integrated_Stock_Folded",
    "MarzGuns.XM177_Integrated_Stock_Deployed",
    "MarzGuns.MP5_Integrated_Stock_Folded",
    "MarzGuns.MP5_Integrated_Stock_Deployed",
    "MarzGuns.MP5SD_Integrated_Stock_Folded",
    "MarzGuns.MP5SD_Integrated_Stock_Deployed",
    "MarzGuns.MAC10_Integrated_Stock_Folded",
    "MarzGuns.MAC10_Integrated_Stock_Deployed",

    -- Bayonets

    "MarzGuns.K98_Bayonet_Attachment",
    "MarzGuns.M5_Bayonet_Attachment",
    "MarzGuns.M9_Bayonet_Attachment",

    --Animated
    "MarzGuns.Bullet_1",
    "MarzGuns.Bullet_2",
    "MarzGuns.Bullet_3",
    "MarzGuns.Bullet_4",
    "MarzGuns.Bullet_5",
    "MarzGuns.Bullet_6",
    "MarzGuns.Bullet_7",
    "MarzGuns.Bullet_8",
    "MarzGuns.Bullet_9",

    "MarzGuns.M16A2_M203_Integrated",
})
